ZSH_GIT_PROMPT_SHOW_UPSTREAM="no"

ZSH_THEME_GIT_PROMPT_PREFIX="[ "
ZSH_THEME_GIT_PROMPT_SUFFIX=" ] "
ZSH_THEME_GIT_PROMPT_SEPARATOR=" |"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[yellow]%}"
ZSH_THEME_GIT_PROMPT_BEHIND=" BH:"
ZSH_THEME_GIT_PROMPT_AHEAD=" AH:"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%} UM:"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%} SG:"
ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%} UG:"
ZSH_THEME_GIT_PROMPT_UNTRACKED=" UT:"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[blue]%} SH:"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%} ✓"

PROMPT='%(?:%F{green}➜:%F{red}➜) %n@%m %F{white}%1~ '
RPROMPT='%f%b$(gitprompt)'
