source ~/.zplug/init.zsh

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history

# Set tmux color to 256
if [ "$TERM" != "xterm-256color" ]; then
    export TERM=xterm-256color
fi

# ZSH plugins
zplug 'Aloxaf/fzf-tab'
zplug 'woefe/git-prompt.zsh', use:'{git-prompt.zsh,simple.zsh}'
zplug 'tom-auger/cmdtime'
zplug 'zsh-users/zsh-autosuggestions'

# Configure default editor
export EDITOR=nvim

# Configure fzf appearance
export FZF_DEFAULT_OPTS="--color=dark,hl:bright-blue,hl+:bright-blue:underline,fg+:yellow:bold:underline,bg+:-1 --reverse"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Source plugins and add commands to $PATH
zplug load

# Add python binary to $PATH
PATH=$PATH:~/.local/bin:~/.cargo/bin

# Set the up and down for history search with prefix
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[k' up-line-or-beginning-search
bindkey '^[j' down-line-or-beginning-search
bindkey '^[h' backward-word
bindkey '^[l' forward-word

# Alias
alias g='git'
alias history='fc -il 1'
alias ls='ls --color=auto'
alias vim='nvim'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
