source ~/.zplug/init.zsh

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history

# Set tmux color to 256
if [ "$TERM" != "xterm-256color" ]; then
    export TERM=xterm-256color
fi

# ZSH plugins
zplug 'woefe/git-prompt.zsh', use:"{git-prompt.zsh,yyprompt.zsh}"
zplug 'Aloxaf/fzf-tab'
zplug 'zsh-users/zsh-autosuggestions'

# Configure fzf appearance
export FZF_DEFAULT_OPTS="--color=dark,hl:bright-blue,hl+:bright-blue:underline,fg+:yellow:bold:underline,bg+:-1 --reverse"

# Configure auto suggestion accept key
bindkey '^k' autosuggest-accept

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Source plugins and add commands to $PATH
zplug load

# Alias
alias g='git'
alias history='fc -il 1'
alias ls='ls --color=auto'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
